<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ValheimServerManager</RootNamespace>
    <AssemblyName>ValheimServerManager</AssemblyName>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Update="Config\Configuration.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <Resource Include="Resources\background.png" />
  </ItemGroup>
</Project>
